package com.yazoni.client.ui;
import com.yazoni.client.YazoniClient;import com.yazoni.client.module.Module;import net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.player.LocalPlayer;import java.util.ArrayDeque;import java.util.Deque;
public final class YazoniHud{private static final Deque<Long> CLICKS=new ArrayDeque<>();private static long sessionStart=System.currentTimeMillis();private static boolean lastAttack,lastUse;private YazoniHud(){}
public static void register(){HudRenderCallback.EVENT.register((g,d)->render(g));}
public static void tick(Minecraft c){if(c.player==null)return;boolean a=c.options.keyAttack.isDown();if(a&&!lastAttack)CLICKS.addLast(System.currentTimeMillis());lastAttack=a;lastUse=c.options.keyUse.isDown();long cut=System.currentTimeMillis()-1000L;while(!CLICKS.isEmpty()&&CLICKS.peekFirst()<cut)CLICKS.removeFirst();}
private static void render(GuiGraphics g){Minecraft c=Minecraft.getInstance();if(c.options.hideGui||c.player==null)return;LocalPlayer p=c.player;int x=HudLayout.infoX,y=HudLayout.infoY;y=line(g,c,"fps-hud","FPS "+c.getFps(),x,y,false);y=line(g,c,"ping-hud","PING "+ping(c),x,y,false);y=line(g,c,"memory-hud","RAM "+memoryMb()+" MB",x,y,false);y=line(g,c,"coordinates",String.format("XYZ %.1f %.1f %.1f",p.getX(),p.getY(),p.getZ()),x,y,true);y=line(g,c,"direction-hud","DIR "+p.getDirection().getName(),x,y,true);y=line(g,c,"cps-counter","CPS "+CLICKS.size(),x,y,false);y=line(g,c,"armor-hud","ARMOR "+p.getArmorValue(),x,y,false);y=line(g,c,"potion-hud","EFFECTS "+p.getActiveEffects().size(),x,y,false);y=line(g,c,"session-timer","SESSION "+sessionTime(),x,y,true);line(g,c,"server-info",serverInfo(c),x,y,true);
if(enabled("keystrokes")){int bx=HudLayout.keysX,by=HudLayout.keysY;key(g,c,"W",c.options.keyUp.isDown(),bx+34,by);key(g,c,"A",c.options.keyLeft.isDown(),bx,by+27);key(g,c,"S",c.options.keyDown.isDown(),bx+34,by+27);key(g,c,"D",c.options.keyRight.isDown(),bx+68,by+27);key(g,c,"LMB",c.options.keyAttack.isDown(),bx,by+54);key(g,c,"RMB",lastUse,bx+50,by+54);}
if(enabled("custom-crosshair")){int cx=c.getWindow().getGuiScaledWidth()/2,cy=c.getWindow().getGuiScaledHeight()/2,s=HudLayout.crosshairSize;g.fill(cx-1,cy-s,cx+1,cy+s+1,0xFFFF9B4A);g.fill(cx-s,cy-1,cx+s+1,cy+1,0xFFFF9B4A);}}
private static int line(GuiGraphics g,Minecraft c,String id,String text,int x,int y,boolean accent){if(!enabled(id))return y;int w=Math.max(82,c.font.width(text)+10);g.fill(x-4,y-4,x+w,y+12,0xB010141A);g.drawString(c.font,text,x,y,accent?0xFFFF9B4A:0xFFFFFFFF);return y+18;}
private static void key(GuiGraphics g,Minecraft c,String text,boolean p,int x,int y){g.fill(x,y,x+32,y+22,p?0xE0FF6900:0xC0202026);g.drawString(c.font,text,x+(32-c.font.width(text))/2,y+7,0xFFFFFFFF);}
private static boolean enabled(String id){Module m=YazoniClient.MODULES.get(id);return m!=null&&m.enabled();}private static int ping(Minecraft c){if(c.getConnection()==null||c.player==null)return 0;var i=c.getConnection().getPlayerInfo(c.player.getUUID());return i==null?0:i.getLatency();}private static long memoryMb(){Runtime r=Runtime.getRuntime();return(r.totalMemory()-r.freeMemory())/(1024*1024);}private static String sessionTime(){long s=(System.currentTimeMillis()-sessionStart)/1000L;return String.format("%02d:%02d:%02d",s/3600,(s/60)%60,s%60);}private static String serverInfo(Minecraft c){if(c.getCurrentServer()!=null)return c.getCurrentServer().name;return c.hasSingleplayerServer()?"SINGLEPLAYER":"MENU";}}
