package com.yazoni.client.ui;
import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;
public final class YazoniHudEditorScreen extends Screen{private String dragging="";private int ox,oy;public YazoniHudEditorScreen(){super(Component.literal("Yazoni HUD Editor"));} @Override protected void init(){HudLayout.clamp(width,height);if(HudLayout.keysX==0&&HudLayout.keysY==0)HudLayout.reset(width,height);}
@Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);g.fill(0,0,width,height,0xB005070A);for(int x=0;x<width;x+=32)g.fill(x,0,x+1,height,0x251FFFFF);for(int y=0;y<height;y+=32)g.fill(0,y,width,y+1,0x251FFFFF);g.drawString(font,"YAZONI HUD EDITOR",18,18,0xFFFFFFFF,true);g.drawString(font,"Drag elements • ESC to close • R to reset",18,34,0xFF9AA1AA);box(g,HudLayout.infoX,HudLayout.infoY,180,190,"HUD INFO");box(g,HudLayout.keysX,HudLayout.keysY,104,80,"KEYSTROKES");g.drawString(font,"FPS 240",HudLayout.infoX+8,HudLayout.infoY+28,0xFFFFFFFF);g.drawString(font,"PING 42",HudLayout.infoX+8,HudLayout.infoY+46,0xFFFFFFFF);g.drawString(font,"XYZ 120.5 64.0 -32.2",HudLayout.infoX+8,HudLayout.infoY+64,0xFFFF9B4A);g.drawString(font,"SESSION 00:12:34",HudLayout.infoX+8,HudLayout.infoY+82,0xFFFFFFFF);g.drawString(font,"W",HudLayout.keysX+44,HudLayout.keysY+20,0xFFFFFFFF,true);g.drawString(font,"A   S   D",HudLayout.keysX+20,HudLayout.keysY+40,0xFFFFFFFF,true);g.drawString(font,"LMB    RMB",HudLayout.keysX+18,HudLayout.keysY+60,0xFFFF9B4A);}
private void box(GuiGraphics g,int x,int y,int w,int h,String title){boolean hvr=inside(mouseX,mouseY,x,y,w,h);g.fill(x,y,x+w,y+h,hvr?0xDD202832:0xCC12171D);g.fill(x,y,x+w,y+2,0xFFFF6900);g.drawString(font,title,x+8,y-12,0xFF8E97A3);}
private boolean inside(double mx,double my,int x,int y,int w,int h){return mx>=x&&mx<=x+w&&my>=y&&my<=y+h;}
@Override public boolean mouseClicked(double mx,double my,int b){if(b!=0)return super.mouseClicked(mx,my,b);if(inside(mx,my,HudLayout.infoX,HudLayout.infoY,180,190)){dragging="info";ox=(int)mx-HudLayout.infoX;oy=(int)my-HudLayout.infoY;return true;}if(inside(mx,my,HudLayout.keysX,HudLayout.keysY,104,80)){dragging="keys";ox=(int)mx-HudLayout.keysX;oy=(int)my-HudLayout.keysY;return true;}return super.mouseClicked(mx,my,b);}
@Override public boolean mouseDragged(double mx,double my,int b,double dx,double dy){if(!dragging.equals("info")&&!dragging.equals("keys"))return super.mouseDragged(mx,my,b,dx,dy);int x=(int)mx-ox,y=(int)my-oy;if(dragging.equals("info")){HudLayout.infoX=x;HudLayout.infoY=y;}else{HudLayout.keysX=x;HudLayout.keysY=y;}HudLayout.clamp(width,height);return true;}
@Override public boolean mouseReleased(double mx,double my,int b){dragging="";return super.mouseReleased(mx,my,b);}
@Override public boolean keyPressed(int key,int scan,int mods){if(key==82){HudLayout.reset(width,height);return true;}return super.keyPressed(key,scan,mods);}
@Override public boolean shouldCloseOnEsc(){return true;}}
