plugins {
    id 'fabric-loom'
    id 'maven-publish'
}

base { archivesName = project.archive_base_name }
version = project.mod_version
group = project.maven_group

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://libraries.minecraft.net/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:" + project.minecraft_version
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:" + project.loader_version
    modImplementation "net.fabricmc.fabric-api:fabric-api:" + project.fabric_api_version
}

loom {
    splitEnvironmentSourceSets()
    mods {
        yazoni {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") { expand "version", project.version }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = "UTF-8"
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
